### PR TITLE
Documentation is fixed about name parameter of config.xml

### PR DESCRIPTION
**Pull request by kamaci**
# Pull request guide

Thank you for considering to improve this cordova-plugin-googlemaps.

When you create a pull request, please make it to **multiple_maps** branch instead of master branch.

Because **the multiple_maps branch is edge version**.

Thank you for your understanding.

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you for your pull request, but I don't think this is any problem.

**Comment by kamaci** [comment]
It makes a confusion about what will be the name of the app in the hand. It doesn't have both English and Non-English app names, it will only have Non-English app name at given example.

On the other hand, English app name is not the app name, but name of the project when you open it at Xcode or Android Studio. 

I think that such a change on documentation will make it much more clear.

**Comment by wf9a5m75** [comment]
Cordova CLI accepts below command.

```
$ cordova create myAppDir test.myapp.app マイプロジェクト
```
"マイプロジェクト" (=myproject) is written in Japanese, which is not English.

Project name could be non-English name. In that case, he/she makes a confusion if both the app and project name are non-English name, regarding of your description.

**Comment by wf9a5m75** [comment]
So far, there is no claim about `(english app name)`. Everybody understand what that means.

**Comment by wf9a5m75** [comment]
Okay, let's vote. I will leave this PR for a month.
5 people post their agree comments with clarify opinions, then I will merge this PR.

The clarify opinion means , not just "+1", but "+1 because .... that's why this PR is good for me" for example.

**Pull request closed without merging**
