### PR TITLE
Translates messages to Brazilian Portuguese (Android & iOS)

### PR DESCRIPTION
**Pull request by thezakman**
Btw, how can I set this in the plugin is there any new argument to use in the config.xml?

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you for your pull request, but there are already translated messages in the multiple_maps branch. (Although I can't read them at all)

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/android/res/values-pt-rPT/pgm_strings.xml

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/src/ios/strings/pt-BR.lproj/pgm_Localizable.strings

**Comment by wf9a5m75** [comment]
> Btw, how can I set this in the plugin is there any new argument to use in the config.xml?

Do you mean how you can set the language?
OS (Android / iOS) select the correct language based on their system language.

**Comment by thezakman** [comment]
Ohhh, sorry I didn't see the multiple_maps branch my bad, how can I use this strings files into my project?

**Comment by thezakman** [comment]
Thank you @wf9a5m75 !

**Comment by wf9a5m75** [comment]
Thank you for sending your pull request anyway.

**Pull request closed without merging**
