### PR TITLE
Fixes memory leak on setIcon (on Android)

### PR DESCRIPTION
**Pull request by lhsantos**
On AsyncImageLoad, even when there's a hit on the cache, a new copy of the cached image is created (image.copy()) and when the icon is changed, the copy created on the previous call is not recycled and memory is leaked. One possible solution would be to return the image object directly stored in the cache (there's no problem, this object is referenced in a single place, the marker). To affect only a single class and to handle more cases (like when a new image is created to draw the label), my fix stores the current icon for each marker in a map and disposes of them when not used anymore.

My minimum demo project ran for hours without crashing, but the used memory keeps increasing slowly. There might be other sources of memory leaks on the plugin.

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you. 
Although there is a reason to copy image, but I will test your code.

**Comment by wf9a5m75** [comment]
I tested your PR, but it didn't effect at all.
But I have been still inspecting in the Android code.
Please wait for a while.

**Comment by lhsantos** [comment]
It doesn't make sense, anyways. s
Should it be necessary to recycle the image even if there are no references to the object? Thank you for checking this, I'm not changing the icon so often anymore, I decided to use a different approach for now, but if it could be possible to animate an icon in general, it would be useful for people developing games.

**Comment by wf9a5m75** [comment]
One thing I don't want to misunderstand that I didn't denied your PR completely.
But if I run your stress test code with your code 10 minutes,
the memory usage is going to increase little by little.

**Start : 172 .75MB**
screen shot 2017-08-28 at 7 45 27 pm

**After 4 minutes: 183.19MB**
screen shot 2017-08-28 at 7 46 44 pm

**After 6 minutes: 186.26MB**
screen shot 2017-08-28 at 7 47 29 pm

**After 8 minutes: 188.55MB**
screen shot 2017-08-28 at 7 47 46 pm

**After 10minutes: 192.41MB**
screen shot 2017-08-28 at 7 48 10 pm

**End: 193.41MB**
screen shot 2017-08-28 at 7 48 23 pm

**Comment by lhsantos** [comment]
The device I tested on is a Moto Z with Android 7.1.1, I think it just handles memory better (and has more memory), the other android device I tested when I first identified this issue crashed much faster. But I don't think my code is attacking the root of the problem. It's unlikely, but there might be a bug on google maps or their graphics library itself. Garbage collector should be handling this case without the need to recycle, I'd expect. I'm not familiar with either to investigate this further...

**Comment by wf9a5m75** [comment]
And one more thing.

The reason of `I tested your PR, but it didn't effect at all.` is this log output.

```
08-28 20:06:12.318 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 1
08-28 20:06:12.428 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 2
08-28 20:06:12.480 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 1
08-28 20:06:12.530 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 3
08-28 20:06:12.594 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 2
08-28 20:06:12.643 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 4
08-28 20:06:12.695 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 3
08-28 20:06:12.748 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 5
08-28 20:06:12.801 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 4
08-28 20:06:12.854 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 6
08-28 20:06:12.907 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 5
08-28 20:06:12.961 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 7
08-28 20:06:13.016 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 6
08-28 20:06:13.075 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 8
08-28 20:06:13.129 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 7
08-28 20:06:13.182 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 9
08-28 20:06:13.235 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 8
08-28 20:06:13.289 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 10
08-28 20:06:13.345 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 9
08-28 20:06:13.398 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 11
08-28 20:06:13.455 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 10
08-28 20:06:13.509 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 12
08-28 20:06:13.563 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 11
08-28 20:06:13.620 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 13
08-28 20:06:13.671 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 12
08-28 20:06:13.726 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 14
08-28 20:06:13.781 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 13
08-28 20:06:13.835 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 15
08-28 20:06:13.888 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 14
08-28 20:06:13.943 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 16
08-28 20:06:13.970 11719-11876/io.ionic.starter W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
08-28 20:06:13.988 11719-11876/io.ionic.starter I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
08-28 20:06:13.988 11719-11876/io.ionic.starter I/DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 4
08-28 20:06:13.999 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 15
08-28 20:06:14.021 11719-11876/io.ionic.starter W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000000b/n/arm64-v8a
08-28 20:06:14.051 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 17
08-28 20:06:14.107 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 16
08-28 20:06:14.159 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 18
08-28 20:06:14.210 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 17
08-28 20:06:14.265 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 19
08-28 20:06:14.317 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 18
08-28 20:06:14.369 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 20
08-28 20:06:14.422 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 19
08-28 20:06:14.475 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 21
08-28 20:06:14.531 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 20
08-28 20:06:14.587 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 22
08-28 20:06:14.640 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 21
08-28 20:06:14.695 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 23
08-28 20:06:14.751 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 22
08-28 20:06:14.805 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 24
08-28 20:06:14.859 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 23
08-28 20:06:14.914 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 25
08-28 20:06:14.970 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 24
08-28 20:06:15.023 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 26
08-28 20:06:15.076 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 25
08-28 20:06:15.131 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 27
08-28 20:06:15.187 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 26
08-28 20:06:15.243 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 28
08-28 20:06:15.300 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 27
08-28 20:06:15.350 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 29
08-28 20:06:15.403 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 28
08-28 20:06:15.456 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 30
08-28 20:06:15.509 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 29
08-28 20:06:15.562 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 31
08-28 20:06:15.615 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 30
08-28 20:06:15.668 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 32
08-28 20:06:15.722 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 31
08-28 20:06:15.780 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 33
08-28 20:06:15.834 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 32
08-28 20:06:15.885 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 34
08-28 20:06:15.939 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 33
08-28 20:06:15.995 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 35
08-28 20:06:16.050 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 34
08-28 20:06:16.108 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 36
08-28 20:06:16.160 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 35
08-28 20:06:16.213 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 37
08-28 20:06:16.266 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 36
08-28 20:06:16.318 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 38
08-28 20:06:16.372 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 37
08-28 20:06:16.426 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 39
08-28 20:06:16.478 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 38
08-28 20:06:16.531 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 40
08-28 20:06:16.586 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 39
08-28 20:06:16.643 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 41
08-28 20:06:16.696 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 40
08-28 20:06:16.750 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 42
08-28 20:06:16.802 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 41
08-28 20:06:16.855 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 43
08-28 20:06:16.908 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 42
08-28 20:06:16.962 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 44
08-28 20:06:17.015 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 43
08-28 20:06:17.071 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 45
08-28 20:06:17.128 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 44
08-28 20:06:17.189 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 46
08-28 20:06:17.239 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 45
08-28 20:06:17.293 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 47
08-28 20:06:17.347 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 46
08-28 20:06:17.404 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 48
08-28 20:06:17.455 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 47
08-28 20:06:17.510 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 49
08-28 20:06:17.569 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 48
08-28 20:06:17.619 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 50
08-28 20:06:17.671 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 49
08-28 20:06:17.724 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 51
08-28 20:06:17.777 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 50
08-28 20:06:17.832 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 52
08-28 20:06:17.888 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 51
08-28 20:06:17.941 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 53
08-28 20:06:17.994 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 52
08-28 20:06:18.049 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 54
08-28 20:06:18.100 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 53
08-28 20:06:18.155 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 55
08-28 20:06:18.214 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 54
08-28 20:06:18.263 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 56
08-28 20:06:18.330 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 55
08-28 20:06:18.372 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 57
08-28 20:06:18.430 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 56
08-28 20:06:18.480 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 58
08-28 20:06:18.533 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 57
08-28 20:06:18.589 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 59
08-28 20:06:18.642 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 58
08-28 20:06:18.695 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 60
08-28 20:06:18.749 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 59
08-28 20:06:18.810 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 61
08-28 20:06:18.861 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 60
08-28 20:06:18.915 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 62
08-28 20:06:18.969 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 61
08-28 20:06:19.024 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 63
08-28 20:06:19.085 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 62
08-28 20:06:19.188 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 64
08-28 20:06:19.229 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 63
08-28 20:06:19.303 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 65
08-28 20:06:19.354 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 64
08-28 20:06:19.413 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 66
08-28 20:06:19.477 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 65
08-28 20:06:19.541 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 67
08-28 20:06:19.601 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 66
08-28 20:06:19.684 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 68
08-28 20:06:19.746 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 67
08-28 20:06:19.802 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 69
```

------

You probably noticed that this plugin manages cache images with counting.

Create a cache image (and store it in memory), then count up when a new marker that uses the same icon url.
Then if the marker remove or changes the icon url, the cache count should decrease.

Since your code flips-flop two images, the count should up and down.

```
---> cacheA = 1
---> cacheB = 1   (cacheA = 0)
---> cacheA = 1   (cacheB = 0)
---> cacheB = 1   (cacheA = 0)
....
```

But your code only increases.

```
08-28 20:06:12.318 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 1
08-28 20:06:12.428 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 2
08-28 20:06:12.480 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 1
08-28 20:06:12.530 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 3
08-28 20:06:12.594 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -1312335134/32x32 = 2
08-28 20:06:12.643 11719-11719/io.ionic.starter D/map_0_1326028010524-marker: ---> -313644830/32x32 = 4
....
```

This means the cacheA and cacheB images are remained forever until you do `map.remove()` or `map.clear()`
------

Then this is the output of the current version.

```
08-28 20:18:55.762 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:55.812 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:55.971 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:56.023 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:56.189 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:56.242 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:56.403 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:56.456 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:56.615 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:56.669 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:56.832 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:56.885 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:57.052 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:57.104 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:57.270 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:57.318 17028-17182/io.ionic.starter W/DynamiteModule: Local module descriptor class for com.google.android.gms.googlecertificates not found.
08-28 20:18:57.325 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:57.338 17028-17182/io.ionic.starter I/DynamiteModule: Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
08-28 20:18:57.339 17028-17182/io.ionic.starter I/DynamiteModule: Selected remote version of com.google.android.gms.googlecertificates, version >= 4
08-28 20:18:57.362 17028-17182/io.ionic.starter W/System: ClassLoader referenced unknown path: /data/data/com.google.android.gms/app_chimera/m/0000000b/n/arm64-v8a
08-28 20:18:57.485 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:57.535 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:57.696 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:57.756 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:57.917 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:57.974 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:58.138 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:58.193 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:58.355 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:58.409 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:58.573 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:58.632 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:58.790 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:58.851 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:59.012 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:59.067 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:59.227 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:59.281 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:59.443 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:59.500 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:59.658 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:59.710 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:18:59.869 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:18:59.922 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:00.082 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:00.135 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:00.293 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:00.346 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:00.508 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:00.566 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:00.728 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:00.782 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:00.953 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:00.998 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:01.165 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:01.218 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:01.376 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:01.430 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:01.592 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:01.646 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:01.810 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:01.864 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:02.030 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:02.085 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:02.244 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
08-28 20:19:02.299 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -1312335134/32x32 = 1
08-28 20:19:02.458 17028-17028/io.ionic.starter D/map_0_93836232007-marker: ----> -313644830/32x32 = 1
````

This is the result I expected.

**Comment by wf9a5m75** [comment]
If you want to confirm this result, you need to modify the PluginMarker.java

around line 1000:

```
        //-------------------------------------------------------
        // Counts up the markers that use the same icon image.
        //-------------------------------------------------------
        if (result.cacheHit) {
          if (marker == null || marker.getTag() == null) {
            callback.onPostExecute(marker);
            return;
          }
          String hitCountKey = "marker_icon_" + marker.getTag();
          pluginMap.objects.put(hitCountKey, result.cacheKey);
          if (!iconCacheKeys.containsKey(result.cacheKey)) {
            iconCacheKeys.put(result.cacheKey, 1);
          } else {
            int count = iconCacheKeys.get(result.cacheKey);
            iconCacheKeys.put(result.cacheKey, count + 1);
          }
          Log.d(TAG, "----> " + result.cacheKey + " = " + iconCacheKeys.get(result.cacheKey));   // <-- insert this line
        }
```

**Comment by wf9a5m75** [comment]
But I understand this code still leaks some memory.
That's why I wrote **But I have been still inspecting in the Android code. Please wait for a while.**

**Comment by wf9a5m75** [comment]
I adapted your idea. But also instance of AsyncLoadImageInterface (callback of AsyncLoadImage) increased memory.

I reuse it, then memory leak is almost solved.

The final results are:

**Start: 185.79MB**
screen shot 2017-08-28 at 11 41 35 pm

**After 2 minutes: 174.83MB**
screen shot 2017-08-28 at 11 41 58 pm

**After 4 minutes: 176.67MB**
screen shot 2017-08-28 at 11 42 17 pm

**After 6 minutes: 178.8M**
screen shot 2017-08-28 at 11 42 33 pm

**After 8 minutes: 179.68MB**
screen shot 2017-08-28 at 11 42 47 pm

**After 10 minutes: 178MB**
screen shot 2017-08-28 at 11 43 05 pm

**End: 179.44MB**
screen shot 2017-08-28 at 11 43 15 pm

**Comment by lhsantos** [comment]
OK, thank you for checking this!

**Pull request closed without merging**
