### PR TITLE
Cordova 9 fix

### PR DESCRIPTION
**Pull request by adamduren**

### CODE REVIEW

**Comment by adamduren** [comment]
@wf9a5m75 I made commit `d4443c0` but travis is building `5e0bf54`. Any idea why?

**Comment by adamduren** [comment]
Again, not sure what is wrong with Travis here is a link to my Travis build of the project showing it works.

https://travis-ci.org/adamduren/cordova-plugin-googlemaps/builds/514913933

**Comment by adamduren** [comment]
@wf9a5m75 any chance of getting this in?

**Comment by wf9a5m75** [comment]
As minimum manner, please fix the errors.
https://travis-ci.org/mapsplugin/cordova-plugin-googlemaps/builds/514913941?utm_source=github_status&utm_medium=notification

**Comment by adamduren** [comment]
Closing as it seems you made the change yourself. Still not sure what's wrong with Travis.

**Pull request closed without merging**
