### PR TITLE
Add support for Cordova iOS 4 and WKWebView.

### PR DESCRIPTION
**Pull request by BozzaDaniel**
As discussed in issue 685. This works with a clean project using WKWebViews.

### CODE REVIEW

**Comment by Hirbod** [comment]
before I'm going to merge this, I will check use your fork to test. Will this work also without WKWebView?

**Comment by Hirbod** [comment]
First of all: thank you. It was a real pain to set up WKWebView (because Ajax calls on file:// were not possible and after installing https://github.com/apache/cordova-plugins/tree/master/wkwebview-engine-localhost - I had to change add 

```php
// respond to preflights
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
  header('Access-Control-Allow-Origin: *');
  header("Access-Control-Allow-Headers: Origin, Authtoken, authtoken, X-Requested-With, Content-Type, Accept");
  exit;
}
header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Headers: Origin, Authtoken, authtoken, X-Requested-With, Content-Type, Accept");
```

to my API in order to receive data. 

Everything works fine so far, but click events on my marker just don't get called. So currently, it's not working fine for me. Any gusses?

**Comment by Hirbod** [comment]
I also see: 

1) White Screen very often (not always) Maybe a timing issue
2) One the App crashes, the 2nd start will have a White Screen (maybe related to that "need a <title> problem"

**Comment by BozzaDaniel** [comment]
It's possible I missed something in the JS-code or in the Marker code. Will check to see if I find something.

As to the two other issues: I changed so the plugin uses <param name="onload" value="true" /> so it would fire the CDVPageDidLoadNotification (has been available since Cordova 2.5.0) and allow the webview background to be changed.

I also had to nil the self.webView.scrollView.delegate when unloading the webView or the app would crash. I had to add a NSNotificationCenter observer for it to work because if I did it in the dispose method it would already be too late (timing issue, check in dealloc in CDVViewController.m for the triggering code).

**Comment by jvence** [comment]
@BozzaDaniel Thanks for this PR. Any update on finishing it up?

**Comment by adrinavarro** [comment]
+1, hoping on an update. Could we maybe sponsor this PR?

**Comment by jagdishadusumalli** [comment]
+1, Thanks @BozzaDaniel for the PR. Waiting for this to be released @Hirbod

**Comment by johnrobertcobbold** [comment]
+1 same here

**Comment by eg271** [comment]
+1 Great work @BozzaDaniel.  

Also getting the white screen issue with both UIWebView and WKWebView on PG ios 4.  Trying the demo code, I can scroll around where the map is meant to be and when I hit the Full Screen button it shows the map having repositioned as expected.  So, it seems to load fine but just not to set up the transparent backdrop correctly.

Can confirm marker click event not called.

map.addGroundOverlay() is also giving "Class not found: GroundOverlay"

**Comment by denkomanceski** [comment]
+1 @adrinavarro great idea. Can we sponsor this PR ? haha. I have some memory leaks as well I want to see if it is with the ios version or Ionic 2 :(

**Comment by 3melectronicmonitoring** [comment]
+1 I need this fixed too!

**Comment by eleva** [comment]
+1, waiting for this.

**Comment by Hirbod** [comment]
I will merge this as soon @BozzaDaniel provide a fixed version, which will not lead into white screens. Would love to merge it. Could you spend some time on that BozzaDaniel to finish?

**Comment by BozzaDaniel** [comment]
Sorry for being MIA for a while. I've been busy working on other projects for a while. I believe the fix for the white screen is simply adding "<param name="onload" value="true" />" to the GoogleMaps feature in plugin.xml. I would have to verify it with a clean project though.

**Comment by denisbabineau** [comment]
@BozzaDaniel not sure what you meant by "" to feature xml but I spent a few minutes debugging this today and believe I have found the root cause of the white screen (AKA transparency not set, AKA CDVPageDidLoadNotification not firing). It's simply due to the plugin being initialized late and only registering for CDVPageDidLoadNotification after the notification has already fired. This would also explain why this issue is not seen in all cases; if your page reloads for instance, odds are the notification will fire then. By default plugins are only loaded when first referenced in JS, setting onload to true in the feature's xml forces the plugin to be initialized at startup.

I applied the fix in my fork, feel free to pull from it @BozzaDaniel / @Hirbod , it's essentially BozzaDaniel's fork already merged with latest + plugin config fixes (plugin id rename & dep hash reference which impacts meteor and/or manual installs).

**Comment by ballenjr** [comment]
@denisbabineau I am trying yours now. I am getting some errors. I am not so good with Objective C, but some seem like they might be related to my settings. Could you offer some insight there? And some seem like they may need to be casted. Again not big on Objective C here.

screen shot 2016-03-09 at 2 57 07 pm

**Comment by denisbabineau** [comment]
@ballenjr sounds like you're trying to integrate in an existing application or modifying/subclassing the MVC, without further context I don't have much to offer. In the context of this issue I'd recommend starting with a clean cordova project with this plugin only. More general questions might be better suited on stackoverflow.

**Comment by ballenjr** [comment]
K, thanks. I am in an established app.

**Comment by ballenjr** [comment]
K, so I am starting from a fresh app. No errors this time. I init the map
and I can see all of the transparencies being applied in html. But the
webview still seems to be blocking with with...

Any ideas?

**Comment by ballenjr** [comment]
The only output I get in xcode is this:
`2016-03-09 16:31:17.076 Test[1851:96980] Using UIWebView
2016-03-09 16:31:17.078 Test[1851:96980] [CDVTimer][handleopenurl] 0.127971ms
2016-03-09 16:31:17.081 Test[1851:96980] [CDVTimer][intentandnavigationfilter] 2.660036ms
2016-03-09 16:31:17.081 Test[1851:96980] [CDVTimer][gesturehandler] 0.119030ms
2016-03-09 16:31:17.083 Test[1851:96980] [CDVTimer][googlemaps] 1.599014ms
2016-03-09 16:31:17.083 Test[1851:96980] [CDVTimer][TotalPluginStartup] 5.261004ms
2016-03-09 16:31:17.494 Test[1851:96980] Resetting plugins due to page load.
2016-03-09 16:31:17.611 Test[1851:96980] Finished load of: file:///var/mobile/Containers/Bundle/Application/F2A2BBBD-6C70-4DED-9C75-A4E6B45F24DA/Test.app/www/index.html
error in __connection_block_invoke_2: Connection interrupted
2016-03-09 16:31:33.431 Test[1851:96980] THREAD WARNING: ['GoogleMaps'] took '496.340820' ms. Plugin should use a background thread.`

And the connection interrupted happens before I init the map.

**Comment by ballenjr** [comment]
Tried doing a page reload to test your above statement. But didn't help.

```
2016-03-09 16:41:42.557 Test[1917:99363] Using UIWebView
2016-03-09 16:41:42.559 Test[1917:99363] [CDVTimer][handleopenurl] 0.110984ms
2016-03-09 16:41:42.562 Test[1917:99363] [CDVTimer][intentandnavigationfilter] 2.597034ms
2016-03-09 16:41:42.563 Test[1917:99363] [CDVTimer][gesturehandler] 0.111997ms
2016-03-09 16:41:42.564 Test[1917:99363] [CDVTimer][googlemaps] 1.612008ms
2016-03-09 16:41:42.564 Test[1917:99363] [CDVTimer][TotalPluginStartup] 5.195975ms
2016-03-09 16:41:42.979 Test[1917:99363] Resetting plugins due to page load.
2016-03-09 16:41:43.129 Test[1917:99363] Finished load of: file:///var/mobile/Containers/Bundle/Application/B4FC9157-0208-41E7-81B8-33694C5F67FA/Test.app/www/index.html
error in __connection_block_invoke_2: Connection interrupted
2016-03-09 16:42:06.680 Test[1917:99363] Resetting plugins due to page load.
2016-03-09 16:42:06.803 Test[1917:99363] Finished load of: file:///var/mobile/Containers/Bundle/Application/B4FC9157-0208-41E7-81B8-33694C5F67FA/Test.app/www/index.html
2016-03-09 16:42:23.237 Test[1917:99363] THREAD WARNING: ['GoogleMaps'] took '393.392822' ms. Plugin should use a background thread.
```

**Comment by denisbabineau** [comment]
I dont think those msgs are related, I tried msg'ing you on gitter can you hop on there? I can try stepping thru the issue. Alternatively try from this link if you didnt get any notifications: https://gitter.im/denisbabineau/cordova-plugin-googlemaps?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by ballenjr** [comment]
In case anyone runs into the same thing...  The problem with my existing app was the work around plugin for WKWebView. I removed it and all was well again.

**Comment by wf9a5m75** [comment]
Could someone give me an example project?

**Comment by wf9a5m75** [comment]
The white screen should be fixed.
screen shot 2016-03-24 at 12 04 56 pm

**Comment by ballenjr** [comment]
One thing to check too is the background-image css properties. Some times
they can be overlooked.

**Comment by wf9a5m75** [comment]
`background-image` css property to which node? And providing a screen capture please.

**Comment by ballenjr** [comment]
Any html node from the top layer to the bottom. In the web inspector. That
was the oversight that I made with the fresh app example that I attempted
above. I could see the transparency classes being applied but I didn't
check that the background-image property was also over ridden. So it
appeared to be being blocked by the webview background color being set to
opaque. But of course I was working from Mr. Babineau's repo. Since at the
time I was getting strange errors from this PR.

I only mentioned it because I read your post and assumed someone could have
been having the same problem. I just noticed that you were not responding
to someone. So sorry for the confusion.

**Comment by eleva** [comment]
Hi, 
I read that support for WkWebView will be added in 1.4 plugin version, which is the current master but not on npm. Is this version stable now? There is a date for release on npm?

Will this work with wkwebview plugins (as for https://github.com/Telerik-Verified-Plugins/WKWebView) or it work just with cordova 4.0.0 and integrated wkwebview engine (https://cordova.apache.org/announcements/2015/12/08/cordova-ios-4.0.0.html)?

**Comment by wf9a5m75** [comment]
The v1.4 is not ready yet since there are some latent bugs. I have been checking all features one by one.

**Pull request merged**
