### PR TITLE
Better handling of info_closed event

### LINKED ISSUE #1536: v2: "Uncaught TypeError: Cannot read property 'getMap' of undefined" in HTMLInfoWindow.close
v2 of plugin (#multiple_maps)-branch

HTMLInfoWindow.close is causing a infinite loop, which is only breaking because of the above error.

Cause:
In HTMLInfoWindow.close
`this.set('marker', undefined)`
triggers a "active_marker_id_changed"-event.

But in Map.js there is:

```
self.on("active_marker_id_changed", function(prevId, newId) {
        if (prevId in self.MARKERS) {
            self.MARKERS[prevId].trigger.call(self.MARKERS[prevId], event.INFO_CLOSE);
        }
        exec(null, null, self.id + "-marker", 'setActiveMarkerId', [newId]);
    });
```

so this again triggers HTMLInfoWindow.close with the difference, that `self.get("marker")` returns undefined now, because there is no marker anymore, it's already closed.

### PR DESCRIPTION
**Pull request by dasois**
Fixes #1536

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you for sending your pull request, but did you consider why the below code is existed in the active_marker_id_changed listener?

```js
 if (prevId in self.MARKERS) { |   |  
   self.MARKERS[prevId].trigger.call(self.MARKERS[prevId], event.INFO_CLOSE); |   |  
}
```

**Comment by dasois** [comment]
I interpreted it as firing the info_close-event on the old marker, if you either click somewhere on the map or on a new marker.

**Comment by wf9a5m75** [comment]
Correct. So at least, that code is required. But also I understand your pointing out. I will fix that.

**Comment by dasois** [comment]
Well we have to options here: Either the InfoWindow fires this event or this Listener. Am I right?

**Comment by wf9a5m75** [comment]
The `INFO_CLOSE` is actually designed for normal marker infoWindow. Not for HtmlInfoWindow.
So the original HtmlInfoWindow does not fire any events on it.

But I changed behavior. 
You can listen the `INFO_OPEN` and `INFO_CLOSE` events for HtmlInfoWindow instance.

```js
var div = document.getElementById("map_canvas");
var map = plugin.google.maps.Map.getMap(div);
map.one(plugin.google.maps.event.MAP_READY, function() {
  var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

  htmlInfoWindow.on(plugin.google.maps.event.INFO_CLOSE, function() {
    alert("---> INFO_CLOSE");
  });
  htmlInfoWindow.on(plugin.google.maps.event.INFO_OPEN, function() {
    alert("---> INFO_OPEN");
  });

  var infoDiv = document.createElement("div");
  infoDiv.innerHTML = "Click the below button.<br>";

  var button = document.createElement("button");
  button.innerText = "Close this infoWindow";
  button.addEventListener("click", function() {
    htmlInfoWindow.close();
  });
  infoDiv.appendChild(button);

  htmlInfoWindow.setContent(infoDiv);

  map.addMarker({
    position: {lat: 0, lng: 0}
  }, function(marker) {

    marker.on(plugin.google.maps.event.MARKER_CLICK, function() {
      htmlInfoWindow.open(marker);
    });
    marker.trigger(plugin.google.maps.event.MARKER_CLICK);

  });
});
```

**Comment by wf9a5m75** [comment]
I changed the code more than you in order to add events. But again, thank you for sending your pull request.

**Comment by dasois** [comment]
Ok I didn't know that INFO_CLOSE ist for the normal Marker Window only. Still I see that the close method get's triggered twice and I think that our `if (!marker)` is a bit of a hack.
I now see that
```
if (prevId in self.MARKERS) {
   self.MARKERS[prevId].trigger.call(self.MARKERS[prevId], event.INFO_CLOSE); 
}
```
is necessary because of the normal InfoWindow.
I think INFO_CLOSE was already triggered by the HTMLInfoWindow before your commit though:
`self.trigger(event.INFO_CLOSE);` ([l. 196](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/HtmlInfoWindow.js#L196))
Or do I missunderstand that line?

**Comment by wf9a5m75** [comment]
No.

This code blocks the second time.Please read the latest code always.  
```js
HTMLInfoWindow.prototype.close = function() {
    var self = this;

    var marker = self.get("marker");
    if (!self.isInfoWindowShown() || !marker) {
      return;
    }
```

**Comment by dasois** [comment]
I read the latest code. I introduced the check for the marker myself in my pull request.
I still don't think that it is a good solution though.

I'll ask the question the other way round. What is the purpose of [this](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/multiple_maps/www/HtmlInfoWindow.js#L196)?

**Comment by wf9a5m75** [comment]
`self.trigger(event.INFO_CLOSE);` is for firing the INFO_CLOSE event for htmlInfoWindow.

```js
var htmlInfoWindow = new plugin.google.maps.HtmlInfoWindow();

htmlInfoWindow.on(plugin.google.maps.event.INFO_CLOSE, function() {

});
```

**Pull request closed without merging**
