### PR TITLE
Detect Visibility tag

### PR DESCRIPTION
**Pull request by livedota**
Detect `Visibility` tag under `Polygon` tag, if value is 0 the polgyon will be not showed on map

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Please provide test kml data file

**Comment by wf9a5m75** [comment]
ping

**Comment by livedota** [comment]
I implemented tag parse code for other tags and [https://pastebin.com/TGfWuRsx](this) is kml example file

**Comment by wf9a5m75** [comment]
Thank you for your contribution.

**Pull request merged**
