### PR TITLE
Rename package/plugin to prevent remapping

### PR DESCRIPTION
**Pull request by eg271**

### CODE REVIEW

**Comment by Hirbod** [comment]
Just started a discussion about that with @wf9a5m75 - let us evaluate everything - then we will merge your request. Thanks so far!

**Comment by Hirbod** [comment]
@eg271 could you also change the line here?
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/package.json#L6

it's easier to have that in one commit :)

**Comment by eg271** [comment]
@Hirbod not sure I follow - would you like me to merge both commits into 1? Is there an easy way to do that just using Github?

**Comment by Hirbod** [comment]
That's possible but not necessariy for 2 changes. Thanks

**Pull request closed without merging**
