### PR TITLE
Allow configuration of padding for marker infowindow in marker styles for Android

### PR DESCRIPTION
**Pull request by xming13**

### CODE REVIEW

**Comment by Hirbod** [comment]
Looks good. As already said in toe other pr, I would merge this if you could provide the same function for iOS - as I want to keep the API as close as possible

**Comment by Hirbod** [comment]
@xming13 found some time for that? would love to merge this

**Comment by xming13** [comment]
As mentioned in the other pr, anyone is welcomed to implement the functionality for the iOS part.

**Comment by wf9a5m75** [comment]
Don't worry. I will check this and implement it in Objective-C if no problem when I have a time.
Thank you for sending this pull request.

**Comment by cadz7** [comment]
Any progress with this?
In the meanwhile, what part of the iOS code manages the left and right padding of the infoWindow?
Thanks

**Comment by wf9a5m75** [comment]
Please use the HtmlInfoWindow of the v2.0.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/README.md

**Pull request closed without merging**
