### PR TITLE
feat: Remove UIWebView Code completely 

### PR DESCRIPTION
**Pull request by HansKrywaa**
# Pull request guide

**Related Issue**: #2746 

I'm not that much into native iOS Development, but i tried my best. I used the [PR](https://github.com/apache/cordova-plugin-inappbrowser/pull/584), mentioned in the related Issue, as template.

- I searched for `UiWebView` in Code and found Usages in:
  - PluginGroundOverlay.m
  - PluginKmlOverlay.m
  - PluginMarker.m
  - PluginTileOverlay.m
  - PluginUtil.h & PluginUtil.m
- I added the `preprocessing #if directives`
- Because the WkWebView Part can be executed from two Places (WK_WEB_VIEW_ONLY is set or `![clsName isEqualToString:@"UIWebView"]`) i created a Methode for this (exclude `PluginTileOverlay.m` as it is just one line)
- I changed the Header File (add the new Methode or edit existing directives (`PluginUtil.h`)
- `npm run test` runs successfully

Seems to work for me - Please give it a Look 🍺

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you for your PR. Let's remove all the code for UIWebView at this time. This action drops some of older Cordova versions, but Apple won't accept the Apps which includes the code of UIWebView anyway. So I think we don't need to take care for UIWebView anymore eventually.

**Comment by HansKrywaa** [comment]
@wf9a5m75 What about the `webViewDidFinishLoad()` Methode in `PluginUtil.m`. Currently this only works with UiWebView, should it be completely removed or changed to WkWebView?

**Comment by HansKrywaa** [comment]
Ok, i removed the `preprocessing  directives` and the existing If Statements and just keep the WkWebView Code.

**Comment by wf9a5m75** [comment]
Sorry for late response. I will check this later today

**Pull request merged**
