### PR TITLE
ignore circle tag, otherwise it interferes with loader

### PR DESCRIPTION
**Pull request by dasois**

### CODE REVIEW

**Comment by wf9a5m75** [comment]
What is the circle tag?

**Comment by wf9a5m75** [comment]
If you are talking about the circle tag of &lt;svg&gt;, the current version does not follow the &lt;svg&gt; element anymore.

**Comment by wf9a5m75** [comment]
The version `2.0.0-beta2-20170714-1245` you use currently is old. The version `2.0.0-beta2-20170725-1025` has different code.

The version `2.0.0-beta2-20170714-1245` (you use this currently)
https://github.com/dasois/cordova-plugin-googlemaps/blob/5dcd3f2b6187bd35468d627697a45f1cd7531a02/www/googlemaps-cdv-plugin.js#L189-L195

The `2.0.0-beta2-20170725-1025` (the latest version at this time)
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/204eecd3d1c54e5514291c5a18817e34a8edb92a/www/googlemaps-cdv-plugin.js#L216-L229

**Comment by dasois** [comment]
you're right, never mind. Closing.

**Pull request closed without merging**
