### PR TITLE
Add setMapToolbarEnabled function for Android

### PR DESCRIPTION
**Pull request by FPCSJames**
This adds a setMapToolbarEnabled function, and a mapToolbar option during map initialization, to hide or show the [map toolbar](https://developers.google.com/maps/documentation/android-api/controls#map_toolbar) on Android devices. It also adds a stub so that calling the function on an iOS device won't result in an error.

Addresses #972.

### CODE REVIEW

**Comment by wf9a5m75** [comment]
I want to implement all features for both OS: Android and iOS.
So if you want to merge this, please create the toolbar for iOS.

**Comment by smcpjames** [comment]
While I understand your goal, it seems a bit nonsensical to try to implement, from scratch, a feature that Google themselves only put into Android, only so that the people who didn't want to see it to begin with can disable it?

**Comment by wf9a5m75** [comment]
>There's support for the iOS-only zIndex property of Marker, the Android-only zoom option in the constructor and setOptions() of Map, and probably more.

These properties are introduced by Hirbod while I left this project for a while.
He broken the rule.

**Comment by wf9a5m75** [comment]
As I wrote above, just create a toolbar for iOS, even if you use it or not.
Otherwise, please wait until when I have enough time.
My private time is really limited (one hour per day, or less), and I'm focusing on implementing multiple maps (working on the multiple_maps branch).
The code will be changed drastically on next version.
(That's why I've been stopping recently merging.)

**Comment by wf9a5m75** [comment]
I implemented to the v2-beta for this feature.
But thank you for sending your pull request.
https://github.com/mapsplugin/v2.0-demo/blob/master/www/Map/setOptions.html#L51

**Comment by FPCSJames** [comment]
Hope it proved useful.

**Pull request closed without merging**
