### PR TITLE
Fixes blank screen issue with crosswalk

### PR DESCRIPTION
**Pull request by FmeuMan**
For issue #638. The white screen is due to setting a white color on the parent container of the webwiew when the plugin start. I think this container is only refreshed when the map is added on background. So if no map is added on the first screen the container stay white.

What i tried :
- map creation at startup (on deviceready) then hide splashscreen on map ready or even later
- no map at startup and getMap(...). Only call it later manualy
- reduce the app and reopen id
- close the app with back button and reopen it
- kill the app and reopen it
- navigator.app.exitApp() and reopen it

What i have not tried : ideas are welcome ;)

Tested with and without crosswalk using cordova 5.3.3 and 5.4.1 with these pugins
```
cordova-plugin-crosswalk-webview 1.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.0 "Device"
cordova-plugin-splashscreen 3.0.0 "Splashscreen"
cordova-plugin-whitelist 1.2.0 "Whitelist"
plugin.google.maps 1.3.8 "phonegap-googlemaps-plugin"
```

### CODE REVIEW

**Comment by Hirbod** [comment]
Thank you very much. I will evaluate your fixed later and when it works as intended, I will merge your code

**Comment by Hirbod** [comment]
@FmeuMan do you have some time to also include your fixes into https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/clusterer ?

The Codebase differes a bit, as there is another controller-setup. You would help me much with that.

**Comment by FmeuMan** [comment]
I'll have a look

**Comment by FmeuMan** [comment]
A more simple version from this PR is #793.
I'll do the custerer branch in the row.

**Pull request closed without merging**
