### PR TITLE
Fixed Dutch translation

### PR DESCRIPTION
**Pull request by Skydragonsz**
Changed the string files for the Dutch translation. (typos)

### CODE REVIEW

**Comment by Skydragonsz** [comment]
Commit 0666fc9 maybe (not sure) fixes #2143

**Comment by Michazzz** [comment]
@Skydragonsz Unfortunately, it doesn't.

**Comment by Skydragonsz** [comment]
@wf9a5m75 can you review this PR

**Comment by wf9a5m75** [comment]
Umm, I can't read Dutch.
But the plugin.xml commit is your correct.

I will review this later when I go to the office. (I haven't eaten breakfast yet)

**Comment by wf9a5m75** [comment]
Although I can't read Dutch at all, but it looks like `lokatie` and `locatie` are the same meaning.
screen shot 2018-03-14 at 9 01 40 am
screen shot 2018-03-14 at 9 01 58 am

Based on number of words on the results of the whole GitHub, it seems `locatie` is popular.
screen shot 2018-03-14 at 9 07 23 am

**Comment by Skydragonsz** [comment]
A lot of words in Dutch ending in "katie" were changed to "catie" in 2005. "Locatie" is one of them. 
It has the same translations because it was correct in 2005. 

> The correct (official) spelling is "locatie" , with a c.

**Pull request merged**
