### PR TITLE
Somes fixes on javascript

### PR DESCRIPTION
**Pull request by FmeuMan**
Fixes a color conversion issue when calling Map.setOptions(...) multiple times
Fixes InfoWindow showing on markers with title "undefined"

### CODE REVIEW

**Comment by Hirbod** [comment]
Thank you. But there was a bug which lead into a crash when title was an integer. Thanks why I converted to string. Did you have take this into account?

**Comment by FmeuMan** [comment]
Oh ok i'll take a look

**Comment by FmeuMan** [comment]
Ok it's working with a number, boolean, empty string, array and object. The only quirk i found is the null value becoming "null".

**Comment by Hirbod** [comment]
Well that's fine! Thanks!

**Pull request merged**
