### PR TITLE
Fix #785

### LINKED ISSUE #785: maxWidth not respected when passing image into marker
The maxWidth is not respected when the passed in image is wider

Changing the following in GoogleMaps.java (around line 1827)

        if (maxWidth > 0) {
          imageView.setMaxWidth(maxWidth);
        }

to

        if (maxWidth > 0) {
          imageView.setMaxWidth(maxWidth);
          imageView.setAdjustViewBounds(true);
        }

resolves the issue for me

### PR DESCRIPTION
**Pull request by FuzzyTree**
Fixes #785 by calling 

```java
imageView.setAdjustViewBounds(true);
```

### CODE REVIEW

**Comment by Hirbod** [comment]
Does iOS work as expected?

**Comment by Hirbod** [comment]
Damn, just closed it by mistake!

**Comment by Hirbod** [comment]
I will fix it manually

**Comment by FuzzyTree** [comment]
unfortunately I don't have an iOS device to test with

**Pull request closed without merging**
