### PR TITLE
Fixed missing custom markers cordova-ios-4

### PR DESCRIPTION
**Pull request by Alex-Sessler**
Adjusted the application directory paths for cordova-ios-4 according to the changes done in https://github.com/apache/cordova-plugin-file

### CODE REVIEW

**Comment by diegognt** [comment]
@wf9a5m75 What needs to be done to merge this? I tested and works for me

**Comment by mudolab** [comment]
how could I install this branch to my project?

**Comment by jpicornellHB** [comment]
@wf9a5m75 Seems that custom icons markers are broken and this is the correct solution. Why it isn't merged?
@mudolab to install it you only have to run `cordova plugins add https://github.com/Alex-Sessler/cordova-plugin-googlemaps#c30f6b4bec7d47821399f0bd6efd45bf1b2fe1c7` with the variables of the api keys. The alphanumeric string is the commit that solves this error.

**Comment by wf9a5m75** [comment]
I have been working on the next version, and the code will be changed significantly.
So I don't merge any pull request at this time.

**Comment by jpicornellHB** [comment]
Thank you @wf9a5m75 ! I'll fork it until you have the next version ready.

**Pull request merged**
