### PR TITLE
Fixed bug `Cannot redefine property: waypoints`

### PR DESCRIPTION
**Pull request by timkovik**
This bug was excepted while try execute addDirectionsRendererSync() method

### CODE REVIEW

**Comment by wf9a5m75** [comment]
When do you need to redefine waypoints?

**Comment by wf9a5m75** [comment]
The `waypoints` property is designed as `non-redefine` property.
You can manipulate it through the methods.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/BaseArrayClass/README.md

By the way, Directions class is not ready to use in public. It means you can not use it in Android and iOS yet.

**Comment by timkovik** [comment]
> When do you need to redefine waypoints?

https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v5/blob/b8efddb1d8238603168e47789ae713b4924ac230/src/app/directions/directions.page.ts#L75 in this example

**Comment by timkovik** [comment]
> Кстати, класс Directions не готов к публичному использованию. Это означает, что вы пока не можете использовать его в Android и iOS.

What it mean? Is it mean that it will not work on production-build app?

And this words sound like `you cant draw routes on your native map with this plugin` 😟

**Comment by wf9a5m75** [comment]
```typescript
if (!this.renderer) {
        // Only first time
      } else {
        // Second time or later
      }
```

**Comment by wf9a5m75** [comment]
> And this words sound like you cant draw routes on your native map with this plugin

I said so.

**Comment by PakMan6** [comment]
Hi guys, Great job so far. Looking forward to android and ios Directions functionality.  I want to stop using maps javascript Api.. but only when the Directions service works well for native devices. Any ideas on when Directions class will be ready for android and ios?
I noticed a few bugs in browser view as well .. addDirectionsRendererSync options (DirectionsRendererOptions) >> suppressMarker, polylineOptions and a few others don't seem to worrk currently.

**Comment by sachi097** [comment]
Hi @timkovik 
Does this fix work on production build app?

Were you able to get directions in production build app after this fix?

**Pull request closed without merging**
