### PR TITLE
Update MyPluginLayer.m

### PR DESCRIPTION
**Pull request by z1ad**
fix issue with not being able to interact with any other view that might have been added
e.g. PhoneGap-Plugin-ListPicker, cordova-plugin-datepicker, etc

Note: this issue only affects iOS. Android already works fine

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you for sending a PR. Please create a demo project, then share it to GitHub.

**Comment by VeteranCoder** [comment]
Hello,

I just wanted to add my two cents to this thread.  We're having the same issue here with the cordova-plugin-datepicker, and are eager to see a fix implemented to this plugin.  Do you have any sense of when the fix might be accepted and included in a release?

**Comment by wf9a5m75** [comment]
If someone provide enough test project on github, I will check it.

**Comment by z1ad** [comment]
https://github.com/z1ad/cordova-plugin-googlemaps/blob/master/test/index.html

cordova plugin add cordova-plugin-listpicker

you will notice it works fine in ios until you add cordova-plugin-googlemaps

after applying PR it works fine with both plugins

**Comment by wf9a5m75** [comment]
Thank you for your cooperation. I will check it later.

**Comment by wf9a5m75** [comment]
Your test code just display the list picker.
However, other people want to use the third party plugins **with maps**.

So, if I display a map, then open a list picker, here it is.

**Comment by wf9a5m75** [comment]
Please try this code by yourself.

```html
<!DOCTYPE html>
<html>

<head>
  <script src="cordova.js"></script>
  <script>
    document.addEventListener('deviceready', function() {
      var mapDiv = document.getElementById('map_canvas');
      var map = plugin.google.maps.Map.getMap(mapDiv);
    });

    function listpicker() {
      try {
        window.plugins.listpicker.showPicker({
            title: "Select an option",
            items: [{
              text: "Option 1",
              value: "1"
            }, {
              text: "Option 2",
              value: "2"
            }, {
              text: "Option 3",
              value: "3"
            }],
            doneButtonLabel: "Select",
            cancelButtonLabel: "Cancel"
          },
          function(item) {
            alert("Selected: " + item);
          },
          function() {
            alert("Cancelled");
          }
        );
      } catch (e) {
        alert("Exception: " + e);
      }

      return false;
    }
  </script>
  <style type="text/css">
    html,
    body {
      width: 100%;
      height: 100%;
    }
  </style>
</head>

<body>
  <div id="map_canvas" style="width:100%;height:100%">
    <a href="#" onclick="return listpicker();">Open listpicker</a>
  </div>
</body>

</html>
```

**Comment by z1ad** [comment]
Your recording is without the PR fix? The list picker is a modal view so we should not be able to interact with the map when it is open. Otherwise we cannot select an option or close the list picker.

**Comment by wf9a5m75** [comment]
No. Using your PR. (Try the code I gave you)

You don't understand how manage the touch event in this plugin.
If you understand this plugin deeply, the location of your code is different.
I will change your code later.

**Comment by z1ad** [comment]
OK I see what you mean. My fix only worked when the map wasnt visible, you are right.
Thank you for fixing it properly.

**Comment by wf9a5m75** [comment]
I modified your code, and merge it to the multiple_maps branch.
Thank you for your PR.

**Comment by datastone** [comment]
I am not being able to interact with cordova-plugin-datepicker after adding cordova-plugin-googlemaps.

**Pull request closed without merging**
