### PR TITLE
Fix App Crash on Resume with java.util.ConcurrentModificationException

### PR DESCRIPTION
**Pull request by HansKrywaa**
#Pull Request

**Related Issue**: #2753

Please give it a Look and merge 😊

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Please write the code for Java 1.6 to older environment (unfortunately).

**Comment by HansKrywaa** [comment]
I'm not sure, but you mean use
```
for(PluginEntry p: pluginsToResume) {}
```

instead of the `forEach` Loop?

**Comment by wf9a5m75** [comment]
Yes. The most `Cordova` users are familiar with only JavaScript, not familiar with Java or Objective-C.
And many users don't update the JDK, or face to trouble to upgrade the JDK version.
That's why they face compile error, then they claim to this repository (because those people can not understand the reason).

I faced the similar cases many times, and they gets me riled up.
In order to avoid this, I write the all code of this plugin with `JDK 1.6` (Java 7).
Thank you for your understanding and cooperation.

**Comment by HansKrywaa** [comment]
Okay, i understand. Thank you for your Explanation. When i search through Google after the Error, i found only Results while removing or adding items while iterating, but that not the Case here? Regarding to [this](https://stackoverflow.com/questions/3184883/concurrentmodificationexception-for-arraylist) the Usage of a Iterator should help, am i correct?

- PR is updated

**Pull request merged**
