### PR TITLE
Update PluginPolygon.java

### PR DESCRIPTION
**Pull request by adappter**
Removed unnecessary code setting the visibility of the polygon hardcoded to true/false.
This is not needed, since the visibility is managed by the PolygonOptions.

### CODE REVIEW

**Comment by wf9a5m75** [comment]
`path.size() > 0` is necessary, because if you create a polyline without points , app would be crashed.

**Comment by adappter** [comment]
Okay then I will revert it and set the polygon options visibility as parameter?

**Comment by wf9a5m75** [comment]
Shit, you sent a pull request to the `master` branch.
But please create a pull request to the `multiple_maps` branch next time, as far as written in https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/pull_request_template.md

**Comment by TdoubleG** [comment]
@webalchemist I'm 100% sure that I did it...strange. Sorry will watch better next time! Thanks for merging.

**Pull request merged**
