### PR TITLE
Implement function to animate marker to specified position for Android

### PR DESCRIPTION
**Pull request by xming13**

### CODE REVIEW

**Comment by Hirbod** [comment]
could you provide the same functionality for iOS? I would like to have a heterogenous api

**Comment by xming13** [comment]
Sure, will do it when I have time

**Comment by Hirbod** [comment]
@xming13 found some time for that? would love to merge this

**Comment by xming13** [comment]
As mentioned in other pr, anyone is welcomed to implement the functionality for the iOS part.

**Comment by wf9a5m75** [comment]
Don't worry. I will check this and implement it in Objective-C if no problem when I have a time.
Thank you for sending this pull request.

**Comment by wf9a5m75** [comment]
Since this is already implemented in v2, I close this pull request.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/utilities/geometry/spherical/interpolate/README.md

**Pull request closed without merging**
