### PR TITLE
add static getMyLocation function

### PR DESCRIPTION
**Pull request by rajeevriitm**
This creates a new static function to access `getMyLocation` without instantiating new `Map`  . It can be called with  `plugin.google.maps.Map.getMyLocation(onSuccess, onError)` .

### CODE REVIEW

**Comment by wf9a5m75** [comment]
Thank you for sending a PR. However not acceptable.
The geolocation should use with map.

If you want to obtain only geolocation, there are many alternatives.

**Comment by rajeevriitm** [comment]
I was using `GeoLocation` plugin but it is failing on many android devices and it is one less plugin. And when tried on some devices , its faster than `Geolocation` plugin.

**Comment by wf9a5m75** [comment]
I think it's almost the same implementation as the `geolocation` plugin.
(And they should tested more than my test on many devices)

**Comment by wf9a5m75** [comment]
So what is the situation you want to get the location without map?

**Comment by rajeevriitm** [comment]
`GeoLocation` is not working on many Xiaomi phones. Issue is open , but I but they seem to suggest its due to webview implementation but latest updates use chrome webview. And I tried their latest from dev branch but that also doesnt work (on some phones).

**Comment by wf9a5m75** [comment]
Okay, then please tell me `what is the situation you want to get the location without map?`

**Comment by rajeevriitm** [comment]
Its something like Tinder . Initially I need location fast no map. But I need map on another page.

**Comment by wf9a5m75** [comment]
Did you consider this plugin also?
https://github.com/pmwisdom/cordova-background-geolocation-services

**Comment by wf9a5m75** [comment]
I merge your PR. Thanks.

**Comment by wf9a5m75** [comment]
Sorry, I revert your PR at once.
I understand your situation, but for the future plan, I will create another static class.
Just a moment please.

**Comment by rajeevriitm** [comment]
Is there any problem with the implementation ?

**Comment by wf9a5m75** [comment]
Your implementation itself does not have a problem.
But I will create another static class, such as `Geolocation` class, to add another methods in the feature.

**Comment by wf9a5m75** [comment]
Ok, I added `Geolocation` class which is static class (internally singleton instance).
As you can see in the commit log, I will implement another methods in the future.

Please reinstall the plugin from the multiple_maps branch.
You can do like this.

```js
plugin.google.maps.Geolocation.getMyLocation(function(result) {

  var div = document.getElementById('map_canvas');
  var map = plugin.google.maps.Map.getMap(div, {
    camera: {
      'target': result.latLng,
      'zoom': 10
    }
  });
  map.on(plugin.google.maps.event.MAP_READY, function() {
    map.addMarker({
      'position': result.latLng,
      'title': result.latLng.toString()
    }, function(marker) {
      marker.showInfoWindow();
    });
  });
});
```

**Comment by rajeevriitm** [comment]
That would be much better. I will check it out and get back to you.

**Pull request merged**
