### PR TITLE
Allow configuration of background-color in marker styles for Android

### PR DESCRIPTION
**Pull request by xming13**

### CODE REVIEW

**Comment by Hirbod** [comment]
@xming13 found some time for that? would love to merge this

**Comment by xming13** [comment]
@Hirbod iirc the last time I looked into it, in iOS it uses the images 'bubble_left' and 'bubble_right' for the marker styling. Changing the background color only affect the middle part. I am not very proficient in Objective-C so anyone is welcomed to implement for the iOS part.

**Comment by wf9a5m75** [comment]
Don't worry. I will check this and implement it in Objective-C if no problem when I have a time.
Thank you for sending this pull request.

**Comment by wf9a5m75** [comment]
Please use the HtmlInfoWindow in v2.0.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/class/HtmlInfoWindow/README.md

**Pull request closed without merging**
